
apiVersion: v1
kind: Service
metadata:
  name: agent-node-0-service
  labels:
    run: agent-node-0-service
spec:
  ports:
  - port: 26656
    protocol: TCP
    name: tcp1
  - port: 26657
    protocol: TCP
    name: tcp2
  selector:
    app: agent-node-0

---
apiVersion: v1
kind: Service
metadata:
  name: agent-node-1-service
  labels:
    run: agent-node-1-service
spec:
  ports:
  - port: 26656
    protocol: TCP
    name: tcp1
  - port: 26657
    protocol: TCP
    name: tcp2
  selector:
    app: agent-node-1

