apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-node
spec:
  serviceName: "kuard"
  replicas: 3
  selector:
    matchLabels:
      app: agent-node
  template:
    metadata:
      labels:
        app: agent-node
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: aea
        image: valory/oracle-poc
      - name: agent-node
        image: tendermint/localnode
        env:
          - name: ID
            value: "0"
          - name: LOG
            value: tendermint.log
        ports:
          - containerPort: 26656
          - containerPort: 26657
        workingDir: /tendermint
        args:
          - wait-for-it.sh
          - -t
          - "120"
          - hardhat:8545
          - --
          - wrapper.sh
          - node
          - --consensus.create_empty_blocks=false
          - --proxy_app=tcp://abci0:26658
        command:
          - /bin/bash
