apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-node
spec:
  serviceName: "agent-node"
  replicas: 2
  selector:
    matchLabels:
      app: agent-node
  template:
    metadata:
      labels:
        app: agent-node
        io.kompose.network/localnet: "true"
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.167.11.3\"]"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: tendermint
        image: valory/localnode
        ports:
          - containerPort: 26656
          - containerPort: 26657
        workingDir: /tendermint
        command: ["/bin/bash"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - wrapper.sh
          - node
          - "--consensus.create_empty_blocks=false"
          - "--proxy_app=tcp://localhost:26658"
        volumeMounts:
          - mountPath: /tendermint
            name: build
      - name: aea
        image: valory/oracle-poc
        args: ["../run.sh", "$(HOSTNAME)"]
        command:
          - /bin/bash
        env: 
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CLUSTERED
            value: "1"
      volumes:
        - name: build
          persistentVolumeClaim:
            claimName: 'build-vol'