site_name: Consensus Algorithms
site_url: https://valory.xyz/
site_description: Consensus algorithms implemented with the open AEA framework.
repo_url: https://github.com/valory-xyz/consensus-algorithms
site_author: developer@valory.xyz

theme: 'material'

strict: true

nav:
  - Home: 'index.md'
  - Preliminaries:
    - Autonomous Economic Agents: 'aea.md'
    - Application BlockChain Interface: 'abci.md'
    - AsyncBehaviour: 'async_behaviour.md'
    - Finite State Machines: 'fsm.md'
    - ABCIApp: 'abci_app.md'
  - Demos:
    - Simple ABCI: 'simple_abci.md'
    - Price Estimation:
      - Introduction: 'price_estimation_demo.md'
      - How it works: 'price_estimation.md'
      - FSM Diagram: 'fsm_diagram.md'
  - Requirements and set-up: 'requirements.md'
  - Miscellaneous:
    - Ethereum: 'ethereum_specifics.md'
    - Delegate call vs call: 'delegate_call.md'
    - Debugging using Tenderly: 'debugging.md'
  - API:
    - Connections:
      - ABCI:
        - Check Dependencies: 'api/connections/abci/check_dependencies.md'
        - Connection: 'api/connections/abci/connection.md'
        - Dialogues: 'api/connections/abci/dialogues.md'
        - Tendermint Decoder: 'api/connections/abci/tendermint_decoder.md'
        - Tendermint Encoder: 'api/connections/abci/tendermint_encoder.md'
        - Scripts: 'api/connections/abci/scripts/genproto.md'
    - Contracts:
      - Gnosis Safe:
        - Contract: 'api/contracts/gnosis_safe/contract.md'
      - Gnosis Safe Proxy Factory:
        - Contract: 'api/contracts/gnosis_safe_proxy_factory/contract.md'
    - Protocols:
      - ABCI:
        - Custom Types: 'api/protocols/abci/custom_types.md'
        - Dialogues: 'api/protocols/abci/dialogues.md'
        - Message: 'api/protocols/abci/message.md'
        - Serialization: 'api/protocols/abci/serialization.md'
    - Skills:
      - Abstract ABCI:
        - Dialogues: 'api/skills/abstract_abci/dialogues.md'
        - Handlers: 'api/skills/abstract_abci/handlers.md'
      - Abstract Round ABCI:
        - Abci App Chain: 'api/skills/abstract_round_abci/abci_app_chain.md'
        - Base: 'api/skills/abstract_round_abci/base.md'
        - Behaviour Utils: 'api/skills/abstract_round_abci/behaviour_utils.md'
        - Behaviour: 'api/skills/abstract_round_abci/behaviours.md'
        - Common: 'api/skills/abstract_round_abci/common.md'
        - Dialogues: 'api/skills/abstract_round_abci/dialogues.md'
        - Handlers: 'api/skills/abstract_round_abci/handlers.md'
        - Models: 'api/skills/abstract_round_abci/models.md'
        - Serializer: 'api/skills/abstract_round_abci/serializer.md'
        - Utils: 'api/skills/abstract_round_abci/utils.md'
      - Oracle Deployment ABCI:
        - Behaviours: 'api/skills/oracle_deployment_abci/behaviours.md'
        - Models: 'api/skills/oracle_deployment_abci/models.md'
        - Payloads: 'api/skills/oracle_deployment_abci/payloads.md'
        - Rounds: 'api/skills/oracle_deployment_abci/rounds.md'
      - Price Estimation ABCI:
        - Behaviours: 'api/skills/price_estimation_abci/behaviours.md'
        - Composition: 'api/skills/price_estimation_abci/composition.md'
        - Dialogues: 'api/skills/price_estimation_abci/dialogues.md'
        - Handlers: 'api/skills/price_estimation_abci/handlers.md'
        - Models: 'api/skills/price_estimation_abci/models.md'
        - Payloads: 'api/skills/price_estimation_abci/payloads.md'
        - Rounds: 'api/skills/price_estimation_abci/rounds.md'
      - Registration ABCI:
        - Behaviours: 'api/skills/registration_abci/behaviours.md'
        - Payloads: 'api/skills/registration_abci/payloads.md'
        - Rounds: 'api/skills/registration_abci/rounds.md'
      - Safe Deployment ABCI:
        - Behaviours: 'api/skills/safe_deployment_abci/behaviours.md'
        - Payloads: 'api/skills/safe_deployment_abci/payloads.md'
        - Rounds: 'api/skills/safe_deployment_abci/rounds.md'
      - Transaction Settlement ABCI:
        - Behaviours: 'api/skills/transaction_settlement_abci/behaviours.md'
        - Payloads: 'api/skills/transaction_settlement_abci/payloads.md'
        - Rounds: 'api/skills/transaction_settlement_abci/rounds.md'
    - Exceptions: exceptions.md
  - Deployment: deployment_description.md


plugins:
    - markdownmermaid

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex
  - attr_list
  - md_in_html

#extra_css:
#    - css/my-styles.css

extra_javascript:
    - https://unpkg.com/mermaid@8.10.1/dist/mermaid.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
