site_name: aea_consensus_algorithm
site_url: https://valory.xyz/
site_description: Consensus algorithms implemented with the AEA framework.
repo_url: https://github.com/valory-xyz/consensus-algorithms
site_author: developer@valory.xyz

theme: 'material'

strict: true

nav:
  - Home: 'index.md'
  - Price Estimation:
    - Demo: 'price_estimation_demo.md'
    - How it works: 'price_estimation.md'
    - System: 'poc-diagram.md'
    - FSM: 'fsm.md'

plugins:
    - markdownmermaid

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex

#extra_css:
#    - css/my-styles.css

extra_javascript:
    - https://unpkg.com/mermaid@8.10.1/dist/mermaid.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
