apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: consensus-algorithms
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
  - image: valory/consensus-algorithms-open-aea
    context: deployments/Dockerfiles/open_aea/
    docker:
      dockerfile: Dockerfile
      buildArgs:
        AEA_VERSION: "0.1.6"
        AEA_AGENT: "valory/oracle_deployable:0.1.0"

  - image: valory/consensus-algorithms-tendermint
    context: deployments/Dockerfiles/localnode/

  - image: valory/consensus-algorithms-hardhat
    context: deployments/Dockerfiles/hardhat

profiles:
  - name: cluster
    patches:
      - op: add
        path: /build/artifacts/0/kaniko
        value: {}
      - op: add
        path: /build/cluster
        value: {}
      - op: remove
        path: /build/artifacts/1
      - op: remove
        path: /build/artifacts/0/docker

  - name: prod
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.develop
      - op: add
        path: /build/artifacts/0/docker/cliFlags
        value: ["--no-cache", "--pull", "--force-rm"]
