apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: open-autonomy
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
  - image: valory/open-autonomy-open-aea
    context: autonomy/data/Dockerfiles/agent/
    docker:
      dockerfile: Dockerfile
      buildArgs:
        AEA_VERSION: "1.16.0"
        AEA_AGENT: "{{.AEA_AGENT}}"


profiles:
  - name: release
    build:
        tagPolicy:
          envTemplate:
            template: "{{.VERSION}}"
        artifacts:

        - image: valory/open-autonomy-open-aea
          context: autonomy/data/Dockerfiles/agent/
          docker:
            noCache: true
            dockerfile: Dockerfile
            buildArgs:
              AEA_VERSION: "1.16.0"
              AEA_AGENT: "{{.AEA_AGENT}}"

        - image: valory/open-autonomy-tendermint
          context: deployments/Dockerfiles/tendermint/
          docker:
            noCache: true
            dockerfile: Dockerfile

        - image: valory/open-autonomy-hardhat
          context: deployments/Dockerfiles/hardhat
          docker:
            noCache: true

        - image: valory/open-autonomy-docs
          docker:
            noCache: true
            dockerfile: deployments/Dockerfiles/documentation/Dockerfile
