apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: build-vol
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: build-vol
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: build-vol
    resources:
        requests:
            storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: config-nodes
spec:
  template:
    spec:
      containers:
      - name: config-nodes
        image: valory/localnode:b02256b@sha256:23eab91d75025d1184af3a4dd719a7b8c4caaa72baae1ba3b7afb6d2d5fe4449
        args: ["testnet",
         "--config",
         "/etc/tendermint/config-template.toml",
         "--o",  ".", "--starting-ip-address",
         "192.167.11.3"
         #"10.244.0.21"
         ]
        volumeMounts:
          - mountPath: /tendermint
            name: build
#           subPath: app2
      volumes:
        - name: build
          persistentVolumeClaim:
            claimName: 'build-vol'
      restartPolicy: Never
  backoffLimit: 4