apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: oracle-poc
profiles:
  - name: deploy
    build:
      artifacts:
      - image: valory/hardhat
        context: ./
        docker:
          dockerfile: DockerFiles/hardhat/Dockerfile
      - image: valory/oracle-poc
        context: ../..
        docker:
          dockerfile: examples/price_estimation/DockerFiles/aea/Dockerfile
      - image: valory/localnode
        context: ./networks/local/localnode/
        docker:
          dockerfile: Dockerfile
    deploy:
      kubectl:
        manifests:
        - kubernetes_configs/build/agent_node*
  - name: configure-remotecluster
    build:
      artifacts:
      - image: valory/oracle-poc
        context: ../..
        docker:
          dockerfile: examples/price_estimation/DockerFiles/aea/Dockerfile
      - image: valory/localnode
        context: ./networks/local/localnode/
        docker:
          dockerfile: Dockerfile
    deploy:
      kubectl:
        manifests:
        - kubernetes_configs/configuration/secret.yaml
        - https://raw.githubusercontent.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/master/deploy/kubernetes/deployment.yaml
        - https://raw.githubusercontent.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/master/deploy/kubernetes/rbac.yaml
        - https://raw.githubusercontent.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/master/deploy/kubernetes/class.yaml
        - kubernetes_configs/configuration/storage/remotestorage.yaml
        - kubernetes_configs/configuration/networking/ip_pools.yaml
        - kubernetes_configs/build/config_job.yaml
  - name: configure-localcluster
    deploy:
      kubectl:
        manifests:
        - kubernetes_configs/configuration/secret.yaml
        - kubernetes_configs/configuration/storage/localstorage.yaml
        - kubernetes_configs/configuration/networking/calico.yaml
  - name: dashboard
    deploy:
      kubectl:
        manifests:
        - https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml


