[rpc]
laddr = "tcp://0.0.0.0:26657"

[consensus]

# How long we wait for a proposal block before prevoting nil
timeout-propose = "5s"

# How much timeout-propose increases with each round
timeout-propose-delta = "1000ms"

# How long we wait after receiving +2/3 prevotes for “anything” (ie. not a single block or nil)
timeout-prevote = "3s"

# How much the timeout-prevote increases with each round
timeout-prevote-delta = "1000ms"

# How long we wait after receiving +2/3 precommits for “anything” (ie. not a single block or nil)
timeout-precommit = "3s"

# How much the timeout-precommit increases with each round
timeout-precommit-delta = "1000ms"

# How long we wait after committing a block, before starting on the new
# height (this gives us a chance to receive some more precommits, even
# though we already have +2/3).
timeout-commit = "3s"